Xanadu Quantum Codebook - Solutions

By arvizu-god

# I.1 All about qubits

All modern classical computation is done using binary digits, or bits. Instead of regular bits, which take one of two values (0 or 1), quantum computing uses qubits. Qubits are physical systems that, just like bits, can exist in a "0" state and a "1" state. For now, you can think of these two states like the two sides of a coin, "heads" or "tails".

Mathematically, the state of a qubit is written as a complex-valued vector with two elements. These vectors, or "state vectors", are denoted by the symbol $|\cdot \rangle\$ , which is called a ket (this is known as Dirac notation). The qubit's "0" and "1" states are expressed as follows: $$|0 \rangle\=\binom{1}{0}\quad |1 \rangle\=\binom{0}{1} $$
The element sitting within the  is the label for that state. These two vectors might look familiar; they look just like the two basis vectors you would use for drawing vectors on a 2-dimensional plane. In fact, these two states form a basis for single-qubit states called the computational basis.

As a consequence of this mathematical description, unlike a bit, a qubit is not limited to being in one of these two states. Qubits can exist in what's known as a superposition of states. A superposition is a linear combination of two basis vectors. Mathematically, $$|\Psi \rangle=\alpha|0 \rangle+\beta|1 \rangle=\alpha\binom{1}{0}+\beta\binom{0}{1}=\binom{\alpha}{\beta}$$
where $\alpha$ and $\beta$ are complex numbers. \alpha and \beta are called amplitudes, and for a state to be valid they must be chosen carefully to satisfy the following criteria:$$|\alpha|^2+|\beta|^2=\alpha\alpha^{*}+\beta\beta^{*}=1$$ where $\alpha^{*}$ and $\beta^{*}$ are the complex conjugates. When $\alpha$ and $\beta$ satisfy this property, a quantum state is called normalized. When a qubit is in a superposition, it is not in both $|0 \rangle$ and $|1 \rangle$ "simultaneously", but is rather in some intermediate combination of the two. If you consider again the analogy of a coin, if $|0 \rangle$ and $|1 \rangle$are "heads" and "tails", a superposition would be like a coin spinning on its edge.


## Codercise I.1.1

Suppose we are given an unnormalized quantum state:$$|\Psi \rangle=\alpha|0 \rangle+\beta|1 \rangle \quad |\alpha|^2+|\beta|^2\neq1$$ We can turn this into an equivalent, valid quantum state by normalizing it. Write a function that, given  and , normalizes this state to $$|\Psi^{'} \rangle=\alpha^{'}|0 \rangle+\beta^{'}|1 \rangle \quad |\alpha^{'}|^2+|\beta^{'}|^2=1$$

### Solution I.1.1

If we have an unnormalized quantum state, we can normalize it by calculating the inner product of $|\Psi \rangle$: $\langle \Psi|\Psi \rangle$ and obtaining a normalization constant that we can then multiply to $\alpha$ and $\beta$ to obtain $\alpha^{'}$ and $\beta^{'}$.$$\langle \Psi|\Psi \rangle=C^2(|\alpha|^2\langle 0|0 \rangle+|\beta|^2\langle 1|1 \rangle)=1$$$$C=\frac{1}{\sqrt{|\alpha|^2+|\beta|^2}}$$
The new state $|\Psi^{'} \rangle$ is equal to: $$|\Psi^{'} \rangle=\alpha^{'}|0 \rangle+\beta^{'}|1 \rangle=\frac{\alpha}{\sqrt{|\alpha|^2+|\beta|^2}}|0 \rangle+\frac{\beta}{\sqrt{|\alpha|^2+|\beta|^2}}|1 \rangle$$

In [2]:
import numpy as np

In [3]:
# Here are the vector representations of |0> and |1>, for convenience
ket_0 = np.array([1, 0])
ket_1 = np.array([0, 1])

def normalize_state(alpha, beta):
    """Compute a normalized quantum state given arbitrary amplitudes.
    
    Args:
        alpha (complex): The amplitude associated with the |0> state.
        beta (complex): The amplitude associated with the |1> state.
        
    Returns:
        array[complex]: A vector (numpy array) with 2 elements that represents
        a normalized quantum state.
    """

    ##################
    # YOUR CODE HERE #
    ##################

    # CREATE A VECTOR [a', b'] BASED ON alpha AND beta SUCH THAT |a'|^2 + |b'|^2 = 1
    
    # RETURN A VECTOR
    c=1/np.sqrt((np.abs(alpha)**2)+(np.abs(beta)**2))
    return c*np.array([alpha,beta])

In [4]:
alpha=2.0+1.0j
beta=-0.3 + 0.4j 
normalize_state(alpha,beta)

array([ 0.87287156+0.43643578j, -0.13093073+0.17457431j])

All qubit state vectors have a dual vector, known as a bra. It is obtained by taking the conjugate transpose of the ket vector:$$\langle\Psi|=\begin{pmatrix}\alpha^{*} & \beta^{*}\end{pmatrix}$$

Together, we can combine a bra and a ket to define an inner product. Given two states $|\Psi \rangle=\alpha|0 \rangle+\beta|1 \rangle$  and $|\phi \rangle=\gamma|0 \rangle+\delta|1 \rangle$, the inner product between them is:$$\langle \phi|\Psi \rangle=\begin{pmatrix}\gamma^{*} & \delta^{*}\end{pmatrix}\begin{pmatrix}\alpha^{*}\\ \beta^{*}\end{pmatrix}=\gamma^{*}\alpha+\delta^{*}\beta$$

The value of the inner product is just a complex number. Loosely, this number tells us how much one state overlaps with another. States between which the inner product is 0 are called orthogonal. The maximum value of the inner product is 1, corresponding to the inner product of a normalized state with itself, $\langle \Psi|\Psi \rangle=1$.

## Codercise I.1.2

Write a function to compute the inner product between two arbitrary states. Then, use it to verify that |0 \rangle and |1 \rangle form an orthonormal basis, i.e., the states are normalized and orthogonal.

### Solution I.1.2
The complex conjugate for a complex number $\alpha=x+iy$ is $\alpha^{*}=x-iy$. If our input are two states, formed by a numpy array, the inner product between them, must be the sum of the products of the elements of our states, e.g if the first state is $\Psi=\binom{\alpha}{\beta}$ and the second state is $\phi=\binom{\gamma}{\delta}$, the inner product of $\Psi$ and $\phi$ is equal to:$$\langle \phi|\Psi \rangle=\begin{pmatrix}\gamma^{*} & \delta^{*}\end{pmatrix}\begin{pmatrix}\alpha^{*}\\ \beta^{*}\end{pmatrix}=\gamma^{*}\alpha+\delta^{*}\beta$$ where $\gamma^{*}$ and $\delta^{*}$ are the complex conjugates of $\gamma$ and $\delta$.

In [10]:
def inner_product(state_1, state_2):
    """Compute the inner product between two states.
    
    Args:
        state_1 (array[complex]): A normalized quantum state vector
        state_2 (array[complex]): A second normalized quantum state vector
        
    Returns:
        complex: The value of the inner product <state_1 | state_2>.
    """
 
    ##################
    # YOUR CODE HERE #
    ##################

    # COMPUTE AND RETURN THE INNER PRODUCT
    return (np.conjugate(state_1[0])*state_2[0])+(np.conjugate(state_1[1])*state_2[1])   


# Test your results with this code
ket_0 = np.array([1, 0])
ket_1 = np.array([0, 1])

print(f"<0|0> = {inner_product(ket_0, ket_0)}")
print(f"<0|1> = {inner_product(ket_0, ket_1)}")
print(f"<1|0> = {inner_product(ket_1, ket_0)}")
print(f"<1|1> = {inner_product(ket_1, ket_1)}")

<0|0> = 1
<0|1> = 0
<1|0> = 0
<1|1> = 1


In [11]:
state_1 = np.array([0.8, 0.6])
state_2 = np.array([1 / np.sqrt(2), 1j / np.sqrt(2)]) 
print(inner_product(state_1, state_2))

(0.565685424949238+0.42426406871192845j)


Let's consider again an arbitrary state of a qubit:$$|\Psi \rangle=\alpha|0 \rangle+\beta|1 \rangle$$

We know that $|\alpha|^2+|\beta|^2=\alpha\alpha^{*}+\beta\beta^{*}=1$, but why must this be the case?

Quantum computing is all about manipulating states of qubits by modifying their state vectors in some way. But at the end of the day, we need to be able to extract an answer from our quantum computer: we need to be able to measure.

Measurement in quantum computing is probabilistic. When we measure a qubit, we can't see that it's in a superposition; we observe the qubit either in state |0 \rangle or state |1 \rangle. If we think back to the coin analogy, measuring a qubit that is in superposition would be like spinning the coin on its edge, slamming your hand down over it, then checking to see whether it is "heads" or "tails".

The amplitudes $\alpha$ and $\beta$ contain the information about the probabilities of the possible outcomes:$$\mathbb{P}(\text{measure}|0 \rangle)=|\alpha|^2$$$$\mathbb{P}(\text{measure}|1 \rangle)=|\beta|^2$$

Since the qubit must be found in one of those two states, the probabilities must sum to $1$.

Measuring a qubit once gets us effectively a single bit of information: which state we observed the qubit in. This doesn't tell us very much about the state, only that this particular basis state is involved in the superposition. In order to get a clearer picture, we have to measure many times, and look at the distribution of outcomes.

## Codercise I.1.3

The function below takes a quantum state vector as input. Complete the function to simulate the outcomes of an arbitrary number of quantum measurements, i.e., return a list of samples $0$ or $1$ based on the probabilities given by the input state.

### Solution I.1.3

If we are given a quantum state vector as input, the elements of the array are the amplitudes of the wave function that describe the system and the probabilities describe the states to which the system collapses after measuring it. Since we want to simulate a quantum measurement process, first we need to compute the probabilities for the state vector as follows:$$|\alpha|^2=\alpha^{*}\alpha$$ The probabilites of the wave function mean that if we want to generate a random sample of different statex the wave function collapsed to, then the randon generator must be weighted to the state probabilities.

In [13]:
def measure_state(state, num_meas):
    """Simulate a quantum measurement process.

    Args:
        state (array[complex]): A normalized qubit state vector. 
        num_meas (int): The number of measurements to take
        
    Returns:
        array[int]: A set of num_meas samples, 0 or 1, chosen according to the probability 
        distribution defined by the input state.
    """

    ##################
    # YOUR CODE HERE #
    ##################
    
    # COMPUTE THE MEASUREMENT OUTCOME PROBABILITIES

    # RETURN A LIST OF SAMPLE MEASUREMENT OUTCOMES
    prob_vector=np.real(state*state.conj())
    return np.random.choice(2,size=num_meas,p=prob_vector)

In [14]:
state = np.array([0.8, 0.6])
measure_state(state, 20)

array([1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0])

We now know how to perform the beginning and end of a quantum algorithm. We can write down the state of a qubit (in other words, "prepare the state"), and using the amplitudes we can simulate the outcomes of measuring it. All we're missing is the step in between: manipulating the qubit in an interesting way!

Qubit states are vectors; to manipulate the vector we need something that we can apply to it that will produce another vector. Furthermore, the new vector must also be a valid, normalized quantum state. What object can we use to achieve this?

Here we turn to linear algebra; quantum operations are represented as matrices. In fact, they are a special type of matrix called a unitary matrix. For some $2\times 2$ complex-valued unitary matrix $U$, the state of the qubit after an operation is:$$|\psi^{'} \rangle=\hat{U}|\psi \rangle$$

You'll learn all about the properties of unitary matrices and some commonly used one in the upcoming nodes. For now, let's simulate the process.

## Codercise I.1.4

Complete the function below to apply the provided quantum operation $U$ to an input state.

### Solution I.1.4
We just have to perform a simple matrix product. For a product between a $2\times 1$ row matrix and a $2\times 2$ matrix, the result is the following:$$\begin{pmatrix}
a & b
\end{pmatrix}
\begin{pmatrix}
c & d \\
e & f
\end{pmatrix}=\begin{pmatrix}
ac+be & ad+bf
\end{pmatrix}$$
For the matrix $$\begin{pmatrix}
\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \\
\frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}}
\end{pmatrix}$$ the product is:$$\begin{pmatrix}
a & b
\end{pmatrix}\begin{pmatrix}
\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \\
\frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}}
\end{pmatrix}=\frac{1}{\sqrt{2}}\begin{pmatrix}a+b & a-b\end{pmatrix}$$


In [15]:
U = np.array([[1, 1], [1, -1]]) / np.sqrt(2)

def apply_u(state):
    """Apply a quantum operation.

    Args:
        state (array[complex]): A normalized quantum state vector. 
        
    Returns:
        array[complex]: The output state after applying U.
    """

    ##################
    # YOUR CODE HERE #
    ##################

    # APPLY U TO THE INPUT STATE AND RETURN THE NEW STATE
    return 1/np.sqrt(2)*np.array([state[0]+state[1],state[0]-state[1]])

You may not have realized it, but you now have all the ingredients to write a very simple quantum simulator that can simulate the outcome of running quantum algorithms on a single qubit! Let's put everything together.

## Codercise I.1.5

Use the functions below to simulate a quantum algorithm that does the following:

* Initialize a qubit in state $|0\rangle$ 
* Apply the provided operation $\hat{U}$
* Simulate measuring the output state 100 times

You'll have to complete a function for initialization, but we've provided functions for the other two.

In [20]:
U = np.array([[1, 1], [1, -1]]) / np.sqrt(2)

def initialize_state():
    """Prepare a qubit in state |0>.
    
    Returns:
        array[float]: the vector representation of state |0>.
    """

    ##################
    # YOUR CODE HERE #
    ##################

    # PREPARE THE STATE |0>   
    return np.array([1,0])


def apply_u(state):
    """Apply a quantum operation."""
    return np.dot(U, state)


def measure_state(state, num_meas):
    """Measure a quantum state num_meas times."""
    p_alpha = np.abs(state[0]) ** 2
    p_beta = np.abs(state[1]) ** 2
    meas_outcome = np.random.choice([0, 1], p=[p_alpha, p_beta], size=num_meas)
    return meas_outcome


def quantum_algorithm():
    """Use the functions above to implement the quantum algorithm described above.
    
    Try and do so using three lines of code or less!
    
    Returns:
        array[int]: the measurement results after running the algorithm 100 times
    """

    ##################
    # YOUR CODE HERE #
    ##################

    # PREPARE THE STATE, APPLY U, THEN TAKE 100 MEASUREMENT SAMPLES
    return measure_state(apply_u(initialize_state()),num_meas=100)


In [21]:
quantum_algorithm()

array([0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1])

That's the end of this Xanadu's Quantum Codebook codercise I.1! See you in the next one. Goodbye!